### ISSUE TITLE
Any possibility to find target server ip/info?

### ISSUE THREAD

**Issue by daidaiworm** [arloor/iptablesUtils#18]
Server B, my target pc.
Server A, pulibc server

After installing this script on A, is there any possiblity to find ip/information about Server B?

Again, thank you for your contibution for this perfect script.

**Comment by arloor** [comment]
It depends.
In china, Home PC is little possible to have a public Internet IPv4 address, because the lack of IPv4 addresses.
In other countries, I don't know if they are in the same situation.

if your family have a public IPv4 address(not start with 192.168 or 10. etc), you still have to configure your router's NAT to cast the router's some port to your PC。

For example, you run a nginx on PC's 80 port. you can cast router's 8080 port to PC's 80 port via router's admin web console. 

then, at the very last, you can use this script to NAT your traffic to your router's 8080 port, your router will NAT it to your PC's 80 port.

Addtionally, the ip of your family router may change(which is truth in China), it is more tricky to monitor the change of router's ip. you need something we called DDNS. It is anotherthing. you may need it or not.

**Comment by daidaiworm** [comment]
Thank you. Maybe I get you confused.
My concern is the privacy and safety.

Server B, pulic static IP with powerful DDOS protection.
Server A, public dynamic IP.

What I'd like to do is hide A's ip. Something like VPN condition.

B是VPS主机有DDOS防护
A是家用服务器，也是公网，购买vps是为了隐私和安全。

请问使用您的脚本，外部人员，可以查看到A的IP或信息吗？

**Comment by arloor** [comment]
看不到的

**Comment by daidaiworm** [comment]
嗯，谢谢啦。再次感谢您的解答。
